// This file was autogenerated by some hot garbage in the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

#ifndef mozilla_dom_{{ ci.scaffolding_class() }}_h
#define mozilla_dom_{{ ci.scaffolding_class() }}_h

#include "mozilla/ErrorResult.h"
#include "mozilla/dom/RootedDictionary.h"
#include "mozilla/dom/ScaffoldingConverter.h"
#include "mozilla/dom/TypedArray.h"
#include "mozilla/dom/UniFFIBinding.h"
#include "mozilla/dom/UniFFIPointer.h"
#include "mozilla/dom/UniFFIPointerType.h"
#include "mozilla/dom/UniFFIRust.h"


namespace mozilla::dom {

// Scaffolding functions from UniFFI
extern "C" {
  {%- for func in ci.iter_user_ffi_function_definitions() %}
  {{ func.rust_return_type() }} {{ func.rust_name() }}({{ func.rust_arg_list() }});
  {% endfor %}
}

class GlobalObject;

{%- for object in ci.object_definitions() %}
{%- let pointer_type = "{}PointerType"|format(object.nm()) %}
// UniFFIPointerType subclass for this pointer type
class {{ pointer_type }} : public UniFFIPointerType {
    public:
        static {{ pointer_type }}& getInstance() {
            static {{ pointer_type }} instance;
            return instance;
        }
    private:
    {{ pointer_type }}() {
            typeName = "{{ ci.cpp_namespace() }}{{ object.nm() }}"_ns;
            destructor = {{ object.ffi_object_free().rust_name() }};
        }
};

{% endfor -%}

class {{ ci.scaffolding_class() }} {
  public:
  {%- for func in ci.iter_user_ffi_function_definitions() %}

  {%- if func.is_async() %}
  static already_AddRefed<Promise> {{ func.nm() }}(
          const GlobalObject& aUniFFIGlobal,
          const Sequence<ScaffoldingType>& aArgs,
          ErrorResult& aUniFFIErrorResult);
  {%- else %}
  static void {{ func.nm() }}(
          const GlobalObject& aUniFFIGlobal,
          const Sequence<ScaffoldingType>& aArgs,
          RootedDictionary<UniFFIScaffoldingCallResult>& aUniFFIReturnValue,
          ErrorResult& aUniFFIErrorResult);
  {%- endif %}
  {%- endfor %}


  {%- for object in ci.object_definitions() %}

  static already_AddRefed<UniFFIPointer> ReadPointer{{ object.nm() }}(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& aArrayBuff, long position);
  static void WritePointer{{ object.nm() }}(const GlobalObject& aUniFFIGlobal, const UniFFIPointer& ptr, const ArrayBuffer& buff, long position, ErrorResult& aError);

  {% endfor %}
};

}  // namespace mozilla::dom

#endif  // mozilla_dom_{{ ci.scaffolding_class() }}_h
