// This file was autogenerated by some hot garbage in the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

#ifndef mozilla_dom_GeometryScaffolding_h
#define mozilla_dom_GeometryScaffolding_h

#include "mozilla/ErrorResult.h"
#include "mozilla/dom/RootedDictionary.h"
#include "mozilla/dom/TypedArray.h"
#include "mozilla/dom/UniFFIRustCallResultBinding.h"
#include "UniFFI.h"

// Scaffolding functions from UniFFI
extern "C" {
double geometry_a4ea_gradient(RustBuffer, RustCallStatus*);

RustBuffer geometry_a4ea_intersection(RustBuffer, RustBuffer, RustCallStatus*);

RustBuffer geometry_a4ea_string_round(RustBuffer, RustCallStatus*);

RustBuffer geometry_a4ea_string_record_round(RustBuffer, RustCallStatus*);

RustBuffer geometry_a4ea_arr_round(RustBuffer, uint32_t, RustCallStatus*);

}

namespace mozilla::dom {

class GlobalObject;

class GeometryScaffolding {
  public:
  static already_AddRefed<Promise> GeometryA4eaGradient(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& ln, ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> GeometryA4eaIntersection(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& ln1, const ArrayBuffer& ln2, ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> GeometryA4eaStringRound(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& s, ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> GeometryA4eaStringRecordRound(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& p, ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> GeometryA4eaArrRound(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& arr, const uint32_t& size, ErrorResult& aUniFFIErrorResult);
};

}  // namespace mozilla::dom

#endif  // mozilla_dom_GeometryScaffolding_h