// This file was autogenerated by some hot garbage in the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

#ifndef mozilla_dom_GeometryScaffolding_h
#define mozilla_dom_GeometryScaffolding_h

#include "mozilla/ErrorResult.h"
#include "mozilla/dom/RootedDictionary.h"
#include "mozilla/dom/TypedArray.h"
#include "mozilla/dom/UniFFIRustCallResultBinding.h"
#include "UniFFI.h"

// Scaffolding functions from UniFFI
extern "C" {
double geometry_4b5d_gradient(RustBuffer, RustCallStatus*);

RustBuffer geometry_4b5d_intersection(RustBuffer, RustBuffer, RustCallStatus*);

RustBuffer geometry_4b5d_string_round(RustBuffer, RustCallStatus*);

RustBuffer geometry_4b5d_string_record_round(RustBuffer, RustCallStatus*);

RustBuffer geometry_4b5d_arr_round(RustBuffer, uint32_t, RustCallStatus*);

RustBuffer geometry_4b5d_map_round(RustBuffer, uint32_t, RustCallStatus*);

RustBuffer geometry_4b5d_enum_round(RustBuffer, RustCallStatus*);

RustBuffer geometry_4b5d_complex_enum_round(RustBuffer, RustCallStatus*);

}

namespace mozilla::dom {

class GlobalObject;

class GeometryScaffolding {
  public:
  static already_AddRefed<Promise> Geometry4b5dGradient(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& ln, ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> Geometry4b5dIntersection(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& ln1, const ArrayBuffer& ln2, ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> Geometry4b5dStringRound(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& s, ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> Geometry4b5dStringRecordRound(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& p, ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> Geometry4b5dArrRound(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& arr, const uint32_t& size, ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> Geometry4b5dMapRound(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& map, const uint32_t& size, ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> Geometry4b5dEnumRound(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& e, ErrorResult& aUniFFIErrorResult);
  static already_AddRefed<Promise> Geometry4b5dComplexEnumRound(const GlobalObject& aUniFFIGlobal, const ArrayBuffer& ce, ErrorResult& aUniFFIErrorResult);
};

}  // namespace mozilla::dom

#endif  // mozilla_dom_GeometryScaffolding_h