// This file was autogenerated by some hot garbage in the `uniffi-bindgen-gecko-js` crate.
// Trust me, you don't want to mess with it!

[ChromeOnly, Exposed=Window]
namespace GeometryScaffolding {
  [Throws]
  Promise<UniFFIScaffoldingCallResult> geometryC382Gradient(UniFFIScaffoldingType... args);
  [Throws]
  Promise<UniFFIScaffoldingCallResult> geometryC382Intersection(UniFFIScaffoldingType... args);
};